branches:
  only: src
language: python
python: '2.7'
sudo: false
env:
  global:
  - secure: WCCaQOt2Gs7RENgngoQ39REgAMyCc1nryvMVMa4cE+PZ8ruxOLhmIEXW45hDmRWQrpWWiB+2ZA6zzzxwDQltenRoOV8QLTSEo6q+ds0ltRM7mGtCsadNJZBnWf1zTHR1IhPdolI5SNGetrSEnaOmsycxa0zeqWbRPltH/lnr5kQBBg4pbnpPDW6x22PdMJaYT4ylDejCxrFYhMT8FgsIvlUcFqpqjHYj9ylXnWFraTU5MMoBQqZUAJor1OY6WXKrr4SIYl1QqIHZXHs6OoxXLltLEkA2Uygw2AVmq5DlG1I7MbZRzVd0IeOBmzk2NfPhLNis26SehVwbWsV7kRIuJ1GCwWkFJvPel0UEpedsePClPUNkW63jlfTOWXDOCM+1yW+JwufO8+2qPy9W4CgCK3EEw9M3B3oe8k4102r7T8TiHupOyHFLKRvocWzzsiAYSm70hsJbP4wuFpR8wKiQ1I8/8fBhR85X5Pd7odWP5F9vDxWnR6xXQEfQPtNBNHUesTvn3QWkFQ5ni0dudjO1khen8hvy8quziqu303SHkT9fcIylOEj4hWFo4D9l75aVFI8/hsmGvXqgoszIdOFTNyp2BXtKfR159fQEZESju1majiIx3WDWg7rnHaEzuPkfYr2bfw2wYwv6opzp9bTxWBBXh4qTdxQHyHIH2qyWFD0=
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: ./generate.sh deploy
